# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b8814d3e71ed04f31b1b29e687d1be937420f225d11baf947fa75820d822c4cf66257bf2e4e47fd24758454415b80b0b03fa6febd6bacc6b4a98264e5723bac

test:
  secret_key_base: 134f3109c6ce276c93a25ad2b0ed233486f22dda86385dca94ed87f786ba912d2a7ccc7038e754468e0d6509743c0e87946362c375b04b3626d5071859a7e841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
